### ISSUE TITLE
could not compile `trust-dns-proto` due to 30 previous errors

### ISSUE THREAD

**Issue by clemencyworld1** [blueOkiris/simple-web-browser#2]
I could not get this to run due to numerous errors. Am not a programmer and no knowledge of rust debugging,
Some of the errors are listed below: 

  Compiling trust-dns-proto v0.20.4
   Compiling gio-sys v0.15.10
error[E0706]: functions in traits cannot be declared `async`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_client_stream.rs:152:5
    |
152 |       async fn connect(addr: SocketAddr) -> io::Result<Self> {
    |       ^----
    |       |
    |  _____`async` because of this
    | |
153 | |         super::tokio::connect(&addr).await.map(AsyncIoTokioAsStd)
154 | |     }
    | |_____^
    |
    = note: `async` trait functions are not currently supported
    = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:37:5
   |
37 |     async fn connect(addr: SocketAddr) -> io::Result<Self>;
   |     -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     `async` because of this
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:34:5
   |
34 |     async fn bind(addr: SocketAddr) -> io::Result<Self>;
   |     -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     `async` because of this
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:46:5
   |
46 |       async fn recv_from(&self, buf: &mut [u8]) -> io::Result<(usize, SocketAddr)> {
   |       ^----
   |       |
   |  _____`async` because of this
   | |
47 | |         futures_util::future::poll_fn(|cx| self.poll_recv_from(cx, buf)).await
48 | |     }
   | |_____^
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:59:5
   |
59 |       async fn send_to(&self, buf: &[u8], target: SocketAddr) -> io::Result<usize> {
   |       ^----
   |       |
   |  _____`async` because of this
   | |
60 | |         futures_util::future::poll_fn(|cx| self.poll_send_to(cx, buf, target)).await
61 | |     }
   | |_____^
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:251:5
    |
251 |       async fn bind(addr: SocketAddr) -> io::Result<Self> {
    |       ^----
    |       |
    |  _____`async` because of this
    | |
252 | |         tokio::net::UdpSocket::bind(addr).await
253 | |     }
    | |_____^
    |
    = note: `async` trait functions are not currently supported
    = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:199:5
    |
199 |     async fn delay_for(duration: Duration);
    |     -----^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |     |
    |     `async` because of this
    |
    = note: `async` trait functions are not currently supported
    = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:202:5
    |
202 |       async fn timeout<F: 'static + Future + Send>(
    |       ^----
    |       |
    |  _____`async` because of this
    | |
203 | |         duration: Duration,
204 | |         future: F,
205 | |     ) -> Result<F::Output, std::io::Error>;
    | |___________________________________________^
    |
    = note: `async` trait functions are not currently supported
    = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:216:5
    |
216 |       async fn delay_for(duration: Duration) {
    |       ^----
    |       |
    |  _____`async` because of this
    | |
217 | |         tokio::time::sleep(duration).await
218 | |     }
    | |_____^
    |
    = note: `async` trait functions are not currently supported
    = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0706]: functions in traits cannot be declared `async`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:220:5
    |
220 |       async fn timeout<F: 'static + Future + Send>(
    |       ^----
    |       |
    |  _____`async` because of this
    | |
221 | |         duration: Duration,
222 | |         future: F,
223 | |     ) -> Result<F::Output, std::io::Error> {
...   |
226 | |             .map_err(move |_| std::io::Error::new(std::io::ErrorKind::TimedOut, "future timed out"))
227 | |     }
    | |_____^
    |
    = note: `async` trait functions are not currently supported
    = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error[E0786]: found invalid metadata files for crate `async_trait`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:33:5
   |
33 | use async_trait::async_trait;
   |     ^^^^^^^^^^^
   |
   = note: invalid metadata version found: /home/clemency/simple-web-browser/target/debug/deps/libasync_trait-b01501f77c01026b.so

error[E0786]: found invalid metadata files for crate `async_trait`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_client_stream.rs:17:5
   |
17 | use async_trait::async_trait;
   |     ^^^^^^^^^^^
   |
   = note: invalid metadata version found: /home/clemency/simple-web-browser/target/debug/deps/libasync_trait-b01501f77c01026b.so

error[E0786]: found invalid metadata files for crate `async_trait`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:17:5
   |
17 | use async_trait::async_trait;
   |     ^^^^^^^^^^^
   |
   = note: invalid metadata version found: /home/clemency/simple-web-browser/target/debug/deps/libasync_trait-b01501f77c01026b.so

error[E0786]: found invalid metadata files for crate `async_trait`
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:14:5
   |
14 | use async_trait::async_trait;
   |     ^^^^^^^^^^^
   |
   = note: invalid metadata version found: /home/clemency/simple-web-browser/target/debug/deps/libasync_trait-b01501f77c01026b.so

error: cannot find attribute `async_trait` in this scope
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_client_stream.rs:150:3
    |
150 | #[async_trait]
    |   ^^^^^^^^^^^

error: cannot find attribute `async_trait` in this scope
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:34:3
   |
34 | #[async_trait]
   |   ^^^^^^^^^^^

error: cannot find attribute `async_trait` in this scope
  --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:25:3
   |
25 | #[async_trait]
   |   ^^^^^^^^^^^

error: cannot find attribute `async_trait` in this scope
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:247:3
    |
247 | #[async_trait]
    |   ^^^^^^^^^^^

error: cannot find attribute `async_trait` in this scope
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:195:3
    |
195 | #[async_trait]
    |   ^^^^^^^^^^^

error: cannot find attribute `async_trait` in this scope
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:214:3
    |
214 | #[async_trait]
    |   ^^^^^^^^^^^

error[E0053]: method `delay_for` has an incompatible type for trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:216:44
    |
216 |     async fn delay_for(duration: Duration) {
    |                                            ^
    |                                            |
    |                                            checked the `Output` of this `async fn`, found opaque type
    |                                            expected `()`, found opaque type
    |
    = note: while checking the return type of the `async fn`
note: type in trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:199:43
    |
199 |     async fn delay_for(duration: Duration);
    |                                           ^
    = note: expected fn pointer `fn(Duration)`
               found fn pointer `fn(Duration) -> impl futures_util::Future<Output = ()>`

error[E0053]: method `timeout` has an incompatible type for trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:223:10
    |
223 |     ) -> Result<F::Output, std::io::Error> {
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `Result`, found opaque type
    |
note: type in trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:205:10
    |
205 |     ) -> Result<F::Output, std::io::Error>;
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected fn pointer `fn(Duration, _) -> Result<<F as futures_util::Future>::Output, futures_io::Error>`
               found fn pointer `fn(Duration, _) -> impl futures_util::Future<Output = Result<<F as futures_util::Future>::Output, futures_io::Error>>`

   Compiling atk-sys v0.15.1
error[E0053]: method `connect` has an incompatible type for trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_client_stream.rs:152:43
    |
152 |     async fn connect(addr: SocketAddr) -> io::Result<Self> {
    |                                           ^^^^^^^^^^^^^^^^ expected enum `Result`, found opaque type
    |
note: type in trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:37:43
    |
37  |     async fn connect(addr: SocketAddr) -> io::Result<Self>;
    |                                           ^^^^^^^^^^^^^^^^
    = note: expected fn pointer `fn(std::net::SocketAddr) -> Result<AsyncIoTokioAsStd<tokio::net::TcpStream>, futures_io::Error>`
               found fn pointer `fn(std::net::SocketAddr) -> impl futures_util::Future<Output = Result<AsyncIoTokioAsStd<tokio::net::TcpStream>, futures_io::Error>>`

error[E0277]: `Result<S, futures_io::Error>` is not a future
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:139:35
    |
139 |         S::Time::timeout(timeout, tcp)
    |         ----------------          ^^^ `Result<S, futures_io::Error>` is not a future
    |         |
    |         required by a bound introduced by this call
    |
    = help: the trait `futures_util::Future` is not implemented for `Result<S, futures_io::Error>`
    = note: Result<S, futures_io::Error> must be a future or must implement `IntoFuture` to be awaited
note: required by a bound in `Time::timeout`
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/lib.rs:202:35
    |
202 |     async fn timeout<F: 'static + Future + Send>(
    |                                   ^^^^^^ required by this bound in `Time::timeout`

error[E0277]: `Result<Result<tcp_stream::TcpStream<S>, futures_io::Error>, futures_io::Error>` is not a future
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:156:15
    |
156 |               })
    |  _______________^
157 | |             .await
    | |__________________^ `Result<Result<tcp_stream::TcpStream<S>, futures_io::Error>, futures_io::Error>` is not a future
    |
    = help: the trait `futures_util::Future` is not implemented for `Result<Result<tcp_stream::TcpStream<S>, futures_io::Error>, futures_io::Error>`
    = note: Result<Result<tcp_stream::TcpStream<S>, futures_io::Error>, futures_io::Error> must be a future or must implement `IntoFuture` to be awaited
    = note: required because of the requirements on the impl of `std::future::IntoFuture` for `Result<Result<tcp_stream::TcpStream<S>, futures_io::Error>, futures_io::Error>`
help: remove the `.await`
    |
156 -             })
156 +             })
    | 

error[E0277]: `Result<S, futures_io::Error>` is not a future
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/tcp/tcp_stream.rs:139:9
    |
139 |         S::Time::timeout(timeout, tcp)
    |         ^^^^^^^^^^^^^^^^ `Result<S, futures_io::Error>` is not a future
    |
    = help: the trait `futures_util::Future` is not implemented for `Result<S, futures_io::Error>`
    = note: Result<S, futures_io::Error> must be a future or must implement `IntoFuture` to be awaited

error[E0277]: `Result<S, futures_io::Error>` is not a future
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:204:27
    |
204 |         S::bind(zero_addr).await
    |         ------------------^^^^^^ `Result<S, futures_io::Error>` is not a future
    |         |
    |         this call returns `Result<S, futures_io::Error>`
    |
    = help: the trait `futures_util::Future` is not implemented for `Result<S, futures_io::Error>`
    = note: Result<S, futures_io::Error> must be a future or must implement `IntoFuture` to be awaited
    = note: required because of the requirements on the impl of `std::future::IntoFuture` for `Result<S, futures_io::Error>`
help: remove the `.await`
    |
204 -         S::bind(zero_addr).await
204 +         S::bind(zero_addr)
    | 

error[E0053]: method `bind` has an incompatible type for trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:251:40
    |
251 |     async fn bind(addr: SocketAddr) -> io::Result<Self> {
    |                                        ^^^^^^^^^^^^^^^^ expected enum `Result`, found opaque type
    |
note: type in trait
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_stream.rs:34:40
    |
34  |     async fn bind(addr: SocketAddr) -> io::Result<Self>;
    |                                        ^^^^^^^^^^^^^^^^
    = note: expected fn pointer `fn(std::net::SocketAddr) -> Result<tokio::net::UdpSocket, futures_io::Error>`
               found fn pointer `fn(std::net::SocketAddr) -> impl futures_util::Future<Output = Result<tokio::net::UdpSocket, futures_io::Error>>`

error[E0277]: the trait bound `DnsResponseFuture: From<Result<Result<DnsResponse, error::ProtoError>, futures_io::Error>>` is not satisfied
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/udp/udp_client_stream.rs:151:10
    |
151 |         .into()
    |          ^^^^ the trait `From<Result<Result<DnsResponse, error::ProtoError>, futures_io::Error>>` is not implemented for `DnsResponseFuture`
    |
    = help: the following implementations were found:
              <DnsResponseFuture as From<Pin<Box<(dyn futures_util::Future<Output = Result<Result<DnsResponse, error::ProtoError>, futures_io::Error>> + Send + 'static)>>>>
              <DnsResponseFuture as From<Pin<Box<F>>>>
              <DnsResponseFuture as From<error::ProtoError>>
              <DnsResponseFuture as From<futures_channel::oneshot::Receiver<Result<DnsResponse, error::ProtoError>>>>
    = note: required because of the requirements on the impl of `Into<DnsResponseFuture>` for `Result<Result<DnsResponse, error::ProtoError>, futures_io::Error>`

error[E0277]: `()` is not a future
   --> /home/clemency/.cargo/registry/src/github.com-1ecc6299db9ec823/trust-dns-proto-0.20.4/src/xfer/dns_multiplexer.rs:350:73
    |
350 |             ActiveRequest::new(complete, request.id(), request_options, Box::new(timeout));
    |             ------------------                                          ^^^^^^^^^^^^^^^^^ `()` is not a future
    |             |
    |             required by a bound introduced by this call
    |
    = help: the trait `futures_util::Future` is not implemented for `()`
    = note: () must be a future or must implement `IntoFuture` to be awaited
    = note: required for the cast to the object type `dyn futures_util::Future<Output = ()> + Send + Unpin`

   Compiling gdk-sys v0.15.1
Some errors have detailed explanations: E0053, E0277, E0706, E0786.
For more information about an error, try `rustc --explain E0053`.
error: could not compile `trust-dns-proto` due to 30 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by blueOkiris** [comment]
I apologize, but I'm not going to work on getting this to build for you since this software is far from complete (there are no releases), and it's not intended to be used right now.

When it's done, and there have been efforts made to make it work on multiple systems, feel free to create a new issue if it still doesn't work, but until it's done, I have no intention to fix any issues
